---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUGS2r7FHq1IR1TQEun+pwQBTDsuswDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTIwMDYxMTAwWhcNMjQxMTE4MDYxMTAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALCPZTpAuJMQ2tU/fCZmcUD0kxlyeU5y8jtiA9Qhsz4bqmvodlDAnEn2Syk04mc6
    42AfNAsZ6nA53zrroNicIV3E851w4dBOnkmzHoIf1eFbzwI01/OrE2FPe2ZVII0I
    uV/jegNW3MzjX4dUCE2VgnDeeiOLOavujDlyRXm46WniYqzMXGjHKsUZfO8lrkua
    GZWbeeMso4ABfOXTQsBunbzDKJPnQTsBufonEI5O3ecRnE+Ee4oyZZekNoMyRVpk
    XugwvCe0A7iMR/aJwvUTBXvrh+wpeKIeToGv8GzJer38LX5NNDqzHCq18JiGApMv
    4f0RqXMGIZ4DhmjZT1sB04Ln0XcYedkSc2bi8FHKEaAn4pje/Oiwsi/TNyAGBm7y
    iL90yu7Yfs+b7VK71HqtZlqeTs/VRxIOVAAADs3kzmsbGkPLaq8FZz0b4cqbI4Uv
    bbXHoG5cQblrt+YWYKwa+/T71t1RBY7D9o42f+2EI0t1NjfmX4oB3YVEMjgLXv5A
    PTSXt+jbos98jFnYXdSNx/MD9AqHgC1XK6CgN2DUcxHd7nm6PJ6oaXRAyHhkBuCK
    DgRkOxIanChg2JYWwiUUOssm5zpv4wpq/3kDFd7ZLtMhZCKa/3BxBI9V1Gr3BV9o
    dVmi00lj0/CLK/bxJ/3kEnRSyekEzDzdXkWPqY2N8ENnAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQbCHhTCJUFWxyP
    TVk/JHCSIe3+QzANBgkqhkiG9w0BAQ0FAAOCAgEAaU1B2BWd+mI9/qIOjCRR4KmQ
    tmm4eWQlIf+KOXi4QIQGFJi2cX3f8HCuroIS1JCUVq6llLSReLSZpDltV8aG0nX1
    +H3JYyKsc34njZOFs/UKER9mQebF2W4SzKPENAPA2d+JJzSBrIVuxo596E0Tl4rF
    Uyb7xc0+mXVUeC5jyulojcQMCIvjhBwscw7ke8K5wrkFBFXL5cXWH4/jGWf1dF18
    j7Fju4SxTrgMHa8N9lk9MG8RJNl7OgIc9i+aREN5MUOd5/s1ntoUnLgvsqUfaVvh
    RDMQKWVyJ28FL1rpmrSDEog4vspAQipi+Vjupev17FjUtWCvegTxApj5odF6qsYA
    5A8J1tXpQiEO2F0O1InGjsPGS4ZIqK2Dk56l0XHFuwpXaLL0Md4Ed1Hzxdk7BuLJ
    9MXQ69cldIgcT8kPYmuksN3C9CoERIACOdQ9BQsVF1YqLXiABYhU7gkjrJA+sj+j
    WlRA8CjJEnADdVRHy8gJpwwfqd8G9LY3vKyZiKk2CUsWsePjQYW7vZhQMU8lND24
    N/baK/V5k1ZBEcu7cvuWRCdfRnGTMKWI8VZDDaLpwffXXRZs3zZHr0PdxXcZzzHJ
    aDwg0Z/MS74UP1uLegnZplQjkR5Dnyzf9aWOfUFguMgTa9WEuOgi1MBqV1orqgZF
    JUZgMu7GK7nee2fuJjc=
    -----END CERTIFICATE-----
    
